### ISSUE TITLE
trying as shell script (login + sendsms)

### ISSUE THREAD

**Issue by klsystem1** [Kajkac/ZTE-MC-Home-assistant-repo#20]
Hi,

I found your project for my MC801a. very nice addon!
Can you tell me how I can use the python scripts for login, and after sending an SMS.
Can I use the python scripts directly in the shell ? How can they called correctly ? 
Thanks,
Klaus

**Comment by Kajkac** [comment]
https://github.com/Kajkac/ZTE-MC-Home-assistant

Here is old repo with basic scripts and how they are called so you can check this out

**Comment by klsystem1** [comment]
thank you, tried zte_tool or zte_sms.py with my ZTE MC801a ip and password from command line with python:
https://github.com/Kajkac/ZTE-MC-Home-assistant/blob/master/old/zte_sms.py

`root@raspberrypi:~/scripts/zte# python zte_sms.py
0650xxxxxx SHELL SCRIPT MESSAGE 24;11;07;11;09;21;+2
0650xxxxxx 005300480045004c004c00200053004300520049005000540020004d004500530053004100470045 24%3B11%3B07%3B11%3B09%3B21%3B%2B2
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/scripts/zte/zte_sms.py", line 102, in <module>
    zteInstance.sendsms()
  File "/root/scripts/zte/zte_sms.py", line 72, in sendsms
    cookie = self.getCookie(password = self.password, LD = self.get_LD())
  File "/root/scripts/zte/zte_sms.py", line 54, in get_LD
    r = requests.get(self.referer + f"goform/goform_get_cmd_process?{payload}", headers=header, data=payload)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
root@raspberrypi:~/scripts/zte#
`
Router: ZTE MC801a
Software Version: BD_ATH3GMC801AV1.0.0B17

**Comment by Kajkac** [comment]
This should be all fixed so i am closing the issue
